version: "3"
services:
  faucet-cache:
    container_name: faucet-cache

    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass Zzv3U8KhACM4

  app:
    container_name: faucet-service
    build: .
    image: faucet-service
    depends_on:
      - faucet-cache
    ports:
      - 3333:3000
    environment:
      PRIVATE_KEY: cc7ea548a3ab8784d0a35f194b7214c0ccc8ea34f92b879d7c5c0299b2a4c452
      RPC_URL: http://172.31.43.24:8545
      COOLDOWN_HOURS: 2
      VALUE: 0.001
      IS_ERC20: true
      ERC20_TOKEN_CONTRACT: 0x34041A31aD627Eb03f92F12736eA3bc67B18f9d5
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: cd3a11d7-6642-4682-a50e-8e30339a6e91
      HCAPTCHA_SECRET: ES_83192b23a46149e2927a137114272cde
      REDIS_URI: redis://:Zzv3U8KhACM4@faucet-cache:6379
      DECIMALS: 8
    links:
      - faucet-cache
